[package]
name = "grpc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
proto-definition = { version = "0.1.0", path = "../proto-definition" }
tokio = { version = "1.40.0", features = ["full"] }
tonic.workspace = true
tonic-health.workspace = true
tower = "0.5.1"
