[package]
name = "proto-definition"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.3"
prost-types = "0.13.3"
tonic.workspace = true

[build-dependencies]
prost-build.workspace = true
tonic-build.workspace = true
walkdir = "2.5.0"
